#!/usr/bin/env bash

NAME="quiet"
CODENAME="quiet"
COPYRIGHT="Copyright (C) 2017 Nathan Shearer"
LICENSE="GNU General Public License 2.0"
VERSION="1.0.0.0"

# \brief Run a command and only show output if an error occurs
# \param $@ The command and its arguments
function quiet_main
{
	local RANDOM64=$(( $RANDOM * $RANDOM * $RANDOM * $RANDOM ))
	"$@" >>/tmp/.quiet.$RANDOM64 2>/tmp/.quiet.$RANDOM64
	local RETURN="$?"
	if [ "$RETURN" -ne 0 ]; then
		cat /tmp/.quiet.$RANDOM64
	fi
	rm -f /tmp/.quiet.$RANDOM64
	return "$RETURN"
}

# \brief Displays the help and exits the program
function quiet_help
{
	#     01234567890123456789012345678901234567890123456789012345678901234567890123456789
	echo "Description:"
	echo "  Run a command and only show output if an error occurs."
	echo
	echo "Usage:"
	echo "  $CODENAME [options] command"
	echo
	echo "Options:"
	echo "  -h, --help"
	echo "    Display this help message and exit."
	echo
	echo "Examples:"
	echo "  $CODENAME ls /"
	echo "  $CODENAME ls /nodir"
	echo
	echo "Version:"
	echo "  $NAME $VERSION"
	echo "  $COPYRIGHT"
	echo "  Licensed under $LICENSE"
	exit
}

#------------------------------------------------------------------------------
# command line arguments
#

if [ $# -eq 1 -a "$1" = "-h" ]; then
	quiet_help
fi

#------------------------------------------------------------------------------
# begin execution
#

quiet_main "$@"
